export const project = [
  {
    id: 4,
    name: "End to End DevOps",
    photo: "/image.png",
    codeUrl: "https://github.com/imbivek08/infra-e2e-devops",
    liveUrl: "#",
    description: "A full-stack blog app deployed through infrastructure automation, GitOps, and container orchestration.",
    tech: ["React", "Node.js", "PostgreSQL", "Docker", "Kubernetes", "ArgoCD"],
  },
  {
    id: 2,
    name: "GameX01",
    photo: "/image.png",
    codeUrl: "https://github.com/imbivek08/gamex01",
    liveUrl: "#",
    description: "A fun auction-style game where players compete through real-time bidding to build the strongest squad.",
    tech: ["TypeScript", "Express", "PostgreSQL", "Next.js", "Socket.IO"],
  },
  {
    id: 3,
    name: "uMate",
    photo: "/image.png",
    codeUrl: "https://github.com/imbivek08/uMate",
    liveUrl: "#",
    description: "A quiz and general knowledge practice platform for social service aspirants preparing for competitive exams.",
    tech: ["TypeScript", "Express", "PostgreSQL", "Next.js"],
  },
  {
    id: 1,
    name: "eDokan",
    photo: "/eDokan.png",
    codeUrl: "https://github.com/imbivek08/online-pasal",
    liveUrl: "#",
    description: "Modern ecommerce experience focused on clean UX, product discovery, and scalable storefront workflows.",
    tech: ["React", "Node.js", "Express", "MongoDB", "Tailwind"],
  },
];
